from google.adk.agents.llm_agent import Agent

summary_agent = Agent(
    model='gemini-2.5-flash',
    name='summary_agent',
    description="Specialist in summarizing travel plans.",
    instruction="""You are a Travel Summarizer.
    1. Look at the finalized itinerary generated by the planner_agent and the weather/hotel details from the research_agent.
    2. Compile a beautiful, cohesive, and 'ready-to-go' final summary for the user.
    3. Use markdown formatting (headers, lists, bolding) to present a premium travel guide.
    4. Provide the final breakdown of total costs and confirm it is within budget.
    5. Make the user feel excited about their trip!""",
    tools=[],
)

